# slurm resource configuration
executor: slurm

# Resources to use if not otherwise specified    
default-resources:
  - mem_mb=50000
  - runtime=1440
  - cores=24
  - slurm_account=sahlab

jobs: 40
latency-wait: 60 
use-conda: True
conda-prefix: "/ref/sahlab/software/miniforge3/envs/smk_envs_phage_pred"
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy

set-resources:

    # Prediction
    reneo_binning:
        mem: 200G
        runtime: 300:00:00
    mmseqs_taxonomy:
        mem: 700G

    # Analysis    
    mmseqs_phage_taxonomy:
        mem: 700G
    phacts_single_prediction:
        mem: 10G
